# Generated by Django 5.2.3 on 2025-08-19 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_article_like_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_comments',
            field=models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
