# Generated by Django 5.2.3 on 2025-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_comment_like_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='new_tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.tag', verbose_name='Теги'),
        ),
    ]
